package GUI.MS;

import GUI.DUAL.mover;
import Menu.Menu;
import MetodoSimplex.Matriz;
import MetodoSimplex.ValidarSimplex;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;



/**
 *
 * @author PUMPKIN
 */
public class Simplex extends javax.swing.JFrame {
    Matriz matriz;
    ValidarSimplex simplex;
    String matrizInicial;
    /**
     * Creates new form Simplex
     */
    public Simplex() {
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(800, 670);
        
        Color cBarra = new Color(210, 224, 237);
        mover mml = new mover(barra);
        barra.addMouseListener(mml);
        barra.addMouseMotionListener(mml);
        barra.setBackground(cBarra);
        barra.setOpaque(true);
        
        ImageIcon logo1 =  new ImageIcon("src/imágenes/descarga.png");
        ImageIcon logo2 =  new ImageIcon("src/imágenes/upiiz.png");
        ImageIcon escoba =  new ImageIcon("src/imágenes/limpia.png");
        ImageIcon C =  new ImageIcon("src/imágenes/close.png");
        ImageIcon M =  new ImageIcon("src/imágenes/IntentoMin.png");
        ImageIcon home =  new ImageIcon("src/imágenes/casita.png");
        Icon homeIcon = new ImageIcon(home.getImage().getScaledInstance(60, 50, Image.SCALE_DEFAULT));
        Icon iconC = new ImageIcon(C.getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));
        Icon iconM = new ImageIcon(M.getImage().getScaledInstance(43, 43, Image.SCALE_DEFAULT));
        Icon escobaIcon = new ImageIcon(escoba.getImage().getScaledInstance(45, 45, Image.SCALE_DEFAULT));
        Icon icono1 = new ImageIcon(logo1.getImage().getScaledInstance(poli.getWidth(), poli.getHeight(), Image.SCALE_DEFAULT));
        Icon icono2 = new ImageIcon(logo2.getImage().getScaledInstance(upiiz.getWidth(), upiiz.getHeight(), Image.SCALE_DEFAULT));
        poli.setIcon(icono1);
        upiiz.setIcon(icono2);
        limpia.setIcon(escobaIcon);
        min.setIcon(iconM);
        close.setIcon(iconC);
        regresar.setIcon(homeIcon);
        inical.setEnabled(false);
        finalT.setEnabled(false);
        lasDos.setEnabled(false);
        falso.setVisible(false);
        
      /*  ImageIcon F =  new ImageIcon("src/imágenes/me.jpg");
        Icon iconF = new ImageIcon(F.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_DEFAULT));
        fondo.setIcon(iconF);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tablas = new javax.swing.ButtonGroup();
        Tablas_tipo = new javax.swing.ButtonGroup();
        close = new javax.swing.JButton();
        min = new javax.swing.JButton();
        barra = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reinstraintsTA = new javax.swing.JTextArea();
        Resolve = new javax.swing.JButton();
        Example = new javax.swing.JButton();
        z = new javax.swing.JTextField();
        poli = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        upiiz = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        limpia = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        finalT = new javax.swing.JRadioButton();
        inical = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        process = new javax.swing.JTextArea();
        lasDos = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        solution = new javax.swing.JTextArea();
        falso = new javax.swing.JRadioButton();
        regresar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Método Simplex");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setContentAreaFilled(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 30, 30));

        min.setBorderPainted(false);
        min.setContentAreaFilled(false);
        min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minActionPerformed(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 40, 30));

        barra.setBackground(new java.awt.Color(210, 224, 237));
        getContentPane().add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 30));

        reinstraintsTA.setColumns(20);
        reinstraintsTA.setRows(5);
        jScrollPane1.setViewportView(reinstraintsTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 240, 155));

        Resolve.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Resolve.setText("Resolver");
        Resolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResolveActionPerformed(evt);
            }
        });
        getContentPane().add(Resolve, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 100, 40));

        Example.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Example.setText("Ejemplo");
        Example.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExampleActionPerformed(evt);
            }
        });
        getContentPane().add(Example, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 90, 40));

        z.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(z, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 140, 30));

        poli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/descarga.png"))); // NOI18N
        getContentPane().add(poli, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 110, 110));

        titulo2.setFont(new java.awt.Font("Prestige Elite Std", 0, 24)); // NOI18N
        titulo2.setText("MÉTODOS CUANTITATIVOS");
        getContentPane().add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, 40));

        titulo.setFont(new java.awt.Font("Prestige Elite Std", 0, 24)); // NOI18N
        titulo.setText("PARA LA TOMA DE DECISIONES");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, 40));

        titulo1.setFont(new java.awt.Font("Prestige Elite Std", 0, 26)); // NOI18N
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("Método Simplex");
        getContentPane().add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 310, 60));

        upiiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/upiiz.png"))); // NOI18N
        getContentPane().add(upiiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 130, 120));

        jLabel2.setFont(new java.awt.Font("Prestige Elite Std", 1, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Maximización");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 200, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setText("Tablas:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 120, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jLabel3.setText("Z = ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 30, 30));

        limpia.setFont(new java.awt.Font("Prestige Elite Std", 0, 16)); // NOI18N
        limpia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/limpia.png"))); // NOI18N
        limpia.setContentAreaFilled(false);
        limpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiaActionPerformed(evt);
            }
        });
        getContentPane().add(limpia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 50, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setText("Restricciones:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 140, 30));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 430, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("Solución:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 140, 40));

        Tablas_tipo.add(finalT);
        finalT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        finalT.setText("Final");
        finalT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalTActionPerformed(evt);
            }
        });
        getContentPane().add(finalT, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        Tablas_tipo.add(inical);
        inical.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inical.setText("Inical");
        inical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicalActionPerformed(evt);
            }
        });
        getContentPane().add(inical, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        process.setEditable(false);
        process.setColumns(20);
        process.setRows(5);
        jScrollPane2.setViewportView(process);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 310, 290));

        Tablas_tipo.add(lasDos);
        lasDos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lasDos.setText("Las Dos");
        lasDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lasDosActionPerformed(evt);
            }
        });
        getContentPane().add(lasDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));

        solution.setEditable(false);
        solution.setColumns(20);
        solution.setRows(5);
        jScrollPane3.setViewportView(solution);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 560, 50));

        Tablas_tipo.add(falso);
        falso.setText("falso");
        getContentPane().add(falso, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, -1));

        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 590, 80, 60));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 830, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExampleActionPerformed
        this.reinstraintsTA.setText("2.5x + y <= 20\n"+"3x + 3y <= 30\n"+"x + 2y <= 16");
        this.z.setText("3x + 4y");
    }//GEN-LAST:event_ExampleActionPerformed

    public JButton getRegresar() {
        return regresar;
    }

    private void limpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiaActionPerformed
        //LIMPIAR
        z.setText("");
        reinstraintsTA.setText("");
        solution.setText("");
        process.setText("");
        inical.setSelected(false);
        finalT.setSelected(false);
        lasDos.setSelected(false);
        lasDos.updateUI();
        inical.setEnabled(false);
        finalT.setEnabled(false);
        lasDos.setEnabled(false);
        falso.setSelected(true);
        this.repaint();
    }//GEN-LAST:event_limpiaActionPerformed

    public JRadioButton getLasDos() {
        return lasDos;
    }

    public JButton getResolve() {
        return Resolve;
    }

    private void ResolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResolveActionPerformed
        // TODO add your handling code here:
        inical.setEnabled(true);
        finalT.setEnabled(true);
        lasDos.setEnabled(true);
        try{
            this.simplex=new ValidarSimplex();
            if(this.simplex.validarZ(this.z.getText())){
                if(this.simplex.validarRestriccionesMax(this.reinstraintsTA.getText())){
                    this.matriz= new Matriz();
                    this.matriz.crearMatriz(simplex);
                    this.matrizInicial=matriz.mostrarMatriz();
                    matriz.resolverMaximizacion();
                    matriz.intrepretacion();
                    this.solution.setText(matriz.intrepretacion()); 
                } else JOptionPane.showMessageDialog(null,"Introduzca restricciones validas");
            }else JOptionPane.showMessageDialog(null,"Introduzca una función objetivo valido");
        }catch(StringIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null,"Introduzca introcciones");
        }
    }//GEN-LAST:event_ResolveActionPerformed

    private void inicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicalActionPerformed
        // Mostrar tabla inicail
        this.process.setText("           TABLA INCIAL           \n"+matriz.variables()+"\n"+matrizInicial);
    }//GEN-LAST:event_inicalActionPerformed

    private void finalTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalTActionPerformed
        // Mostrar tabla final
        this.process.setText("           TABLA FINAL           \n"+matriz.variables()+"\n"+matriz.mostrarMatriz());
    }//GEN-LAST:event_finalTActionPerformed

    public void lasDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lasDosActionPerformed
        // TODO add your handling code here:
        this.process.setText("           TABLA INCIAL           \n"+matriz.variables()+"\n"+matrizInicial
        +"\n\n           TABLA FINAL           \n"+matriz.variables()+"\n"+matriz.mostrarMatriz());
    }//GEN-LAST:event_lasDosActionPerformed

    public void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        Menu d = new Menu();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
        //MINIMIZAR
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        //CLOSE
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    public JTextArea getReinstraintsTA() {
        return reinstraintsTA;
    }

    public JTextField getZ() {
        return z;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simplex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Example;
    private javax.swing.JButton Resolve;
    private javax.swing.ButtonGroup Tablas;
    private javax.swing.ButtonGroup Tablas_tipo;
    private javax.swing.JLabel barra;
    private javax.swing.JButton close;
    private javax.swing.JRadioButton falso;
    private javax.swing.JRadioButton finalT;
    private javax.swing.JLabel fondo;
    private javax.swing.JRadioButton inical;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton lasDos;
    private javax.swing.JButton limpia;
    private javax.swing.JButton min;
    private javax.swing.JLabel poli;
    private javax.swing.JTextArea process;
    private javax.swing.JButton regresar;
    private javax.swing.JTextArea reinstraintsTA;
    private javax.swing.JTextArea solution;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel upiiz;
    private javax.swing.JTextField z;
    // End of variables declaration//GEN-END:variables
}
